"""create feedback_responses table

Revision ID: 1a5833755e2e
Revises: 92ed55d9c33a
Create Date: 2025-06-17 19:35:13.067877

"""
from collections.abc import Sequence

import sqlalchemy as sa

# see https://stackoverflow.com/a/69063829 for sqlmodel
import sqlmodel
import sqlmodel.sql.sqltypes  # noqa: F401
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1a5833755e2e'
down_revision: str | None = '92ed55d9c33a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbackresponse',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exam_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbackresponse_group_id'), 'feedbackresponse', ['group_id'], unique=False)
    op.create_index(op.f('ix_feedbackresponse_student_id'), 'feedbackresponse', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbackresponse_student_id'), table_name='feedbackresponse')
    op.drop_index(op.f('ix_feedbackresponse_group_id'), table_name='feedbackresponse')
    op.drop_table('feedbackresponse')
    # ### end Alembic commands ###
